from __future__ import annotations

import pathlib
import re
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github" / "workflows" / "cloudflare-candidate-validation.yml"
LOCK = ROOT / "requirements-ci.txt"


class CloudflareCandidateCIContractTests(unittest.TestCase):
    def test_ci_is_read_only_secret_free_hash_locked_and_candidate_focused(self) -> None:
        workflow = WORKFLOW.read_text(encoding="utf-8")
        lock = LOCK.read_text(encoding="utf-8")

        self.assertIn("pull_request:", workflow)
        self.assertIn("push:", workflow)
        self.assertIn("codex/cloudflare-os-foundation", workflow)
        self.assertNotIn("pull_request_target", workflow)
        self.assertIn("contents: read", workflow)
        self.assertIn("ubuntu-24.04", workflow)
        self.assertIn("name: Trusted Cloudflare candidate validation", workflow)
        self.assertIn("actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803", workflow)
        self.assertIn("actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97", workflow)
        self.assertIn('python-version: "3.12.10"', workflow)
        self.assertIn("actions/setup-node@820762786026740c76f36085b0efc47a31fe5020", workflow)
        self.assertIn('node-version: "24.14.0"', workflow)
        self.assertIn("--require-hashes -r requirements-ci.txt", workflow)
        self.assertIn("tests.test_cloudflare_candidate_ci", workflow)
        self.assertIn("tests.test_cloudflare_edge_candidate", workflow)
        self.assertIn("tests.test_cloudflare_os_candidate", workflow)
        self.assertIn("tests.test_cloudflare_os_local_runtime_evaluation", workflow)
        self.assertIn("tests.test_cloudflare_os_security_overlay", workflow)
        self.assertIn("validate_cloudflare_edge_candidate.py --root .", workflow)
        self.assertIn("validate_cloudflare_os_candidate.py", workflow)
        self.assertIn("validate_cloudflare_os_local_runtime_evaluation.py --json", workflow)
        self.assertIn("validate_cloudflare_os_security_candidate.py", workflow)
        self.assertIn("git status --porcelain", workflow)
        self.assertIn("node --test tests/node/test_cloudflare_voice_review.mjs", workflow)

        forbidden = (
            "CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID", "secrets.",
            "wrangler", "versions upload", "deploy", "environment:",
        )
        self.assertFalse(any(marker in workflow for marker in forbidden))

        # `requirements-ci.txt` is the single hash-locked dependency set shared by
        # every workflow in this repository, generated by pip-compile
        # --generate-hashes. Assert the properties that matter — every dependency
        # pinned and hashed, nothing unhashed, no weak digest — rather than a
        # dependency count, which changes whenever the shared closure does.
        requirements = [
            line
            for line in lock.splitlines()
            if line and not line.startswith(("#", " ", "\t"))
        ]
        self.assertTrue(requirements)
        pinned = re.compile(r"^[a-z0-9._-]+(\[[a-z0-9,._-]+\])?==[^ ]+ \\$")
        for line in requirements:
            self.assertRegex(line, pinned)
        digests = re.findall(r"--hash=sha256:([0-9a-f]{64})", lock)
        self.assertEqual(len(digests), len(set(digests)))
        self.assertGreaterEqual(len(digests), len(requirements))
        self.assertNotIn("--hash=md5:", lock)
        self.assertNotIn("--hash=sha1:", lock)
        self.assertIn("jsonschema[format-nongpl]==", lock)


if __name__ == "__main__":
    unittest.main()
